version: '3'
 
services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cateno
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - mt-network
  spring-boot-jpa-docker-webapp:
    build:
      context: ./
    image: cateno:latest
    depends_on:
      - docker-mysql
    ports:
      - 8180:8180
    networks:
      - mt-network
    environment:
      - WAIT_HOSTS=docker-mysql
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=cateno   
      - DATABASE_PORT=3306
      - DATABASE_PLATFORM=mysql
networks:
  mt-network:
    driver: bridge