version: '3.5'
 
services:
#BD
  mysqldb:
    image: mysql:8
    container_name: cateno-db-app
    networks:
    - network-cateno
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cateno
    restart: always

#APP
  cateno:
    container_name: cateno
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: mysqldb:3306
      WAIT_HOSTS_TIMEOUT: 120
    ports:
     - "8180:8180"
    expose:
      - "8180"
    links:
      - mysqldb
    depends_on:
      - mysqldb
#REDE  
networks:
  network-cateno: null