project:
    stacktrace-error: true
        
info:
    version: ${project.version}
    jdk: 11

server: 
    servlet: 
        contextPath: /poc/rest/
    port: 8180


management:
    endpoint:
        health:
            show-details: "ALWAYS"
        web:
            base-path: "/app"
    endpoints:
        web:
            base-path: "/app"

spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 50MB
    main:
        allow-bean-definition-overriding: true
    jpa: 
        properties: 
            hibernate:
                ddl-auto: update
        show-sql: true
        batch:
            size: 100
    jackson: 
        default-property-inclusion: non_empty
    session:
        timeout: 5s
    datasource:
        url: jdbc:mysql://mysqldb/poc
        username: root
        password: root
        platform: mysql
        initialization-mode: always
        validationQuery: SELECT 1

api:
    bc:
        url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)    
